services:
  - type: web
    name: arsip-desa
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    disk:
      name: nextcloud_data
      mountPath: /var/www/html
      sizeGB: 5
    envVars:
      - key: POSTGRES_HOST
        fromService:
          type: pserv
          name: nextcloud-db
      - key: POSTGRES_USER
        fromDatabase:
          name: nextcloud-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: nextcloud-db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: nextcloud-db
          property: database
      - key: NEXTCLOUD_ADMIN_USER
        value: admin
      - key: NEXTCLOUD_ADMIN_PASSWORD
        value: admin123

databases:
  - name: nextcloud-db
    plan: free
